CREATE TABLE TRABAJADOR (SEGURO_SOCIAL INTEGER,
NOMBRE VARCHAR2(80), PATERNO VARCHAR2(80),
CONSTRAINT PK_TRABAJADOR PRIMARY KEY(SEGURO_SOCIAL));

--creamos la secuencia para la nomina 
CREATE SEQUENCE SEC_NOMINA
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

--PROCEDIMIENTO PARA GUARADAR TRABAJADOR
CREATE OR REPLACE PROCEDURE GUARDAR_TRABAJADOR(MY_ID IN INTEGER ,
MY_NOMBRE IN VARCHAR2,MY_PATERNO IN VARCHAR2) AS 
BEGIN
INSERT INTO TRABAJADOR VALUES (MY_ID_NOMBRE,MY_PATERNO);
END;
/
